import uuid
from datetime import datetime
from typing import Optional
from sqlalchemy import String, Text, DateTime, Float, JSON, ForeignKey, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID
from app.database import Base


class Alert(Base):
    """
    A surveillance alert generated by the pattern detection engine.
    Fully data-agnostic: pattern type, evidence, and confidence are computed
    at runtime based on whatever data was uploaded.
    """
    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    investigation_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("investigations.id"), nullable=False)

    # Who / What
    trader_id: Mapped[str] = mapped_column(String(100), nullable=False)
    symbol: Mapped[str] = mapped_column(String(50), nullable=False)

    # Pattern metadata
    pattern: Mapped[str] = mapped_column(String(100), nullable=False)
    # Values: Spoofing | Quote Stuffing | Momentum Ignition | Pump & Dump
    #         Wash Trading | Layering | Close Manipulation
    severity: Mapped[str] = mapped_column(String(20), nullable=False)   # CRITICAL | HIGH | MEDIUM | LOW
    confidence: Mapped[str] = mapped_column(String(20), default="Medium")  # High | Medium | Low

    # Time range of detected pattern
    start_time: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    end_time: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)

    # Evidence — stored as JSON dict (computed by surveillance engine)
    # Example keys: cancellation_ratio, order_count, cancelled_volume, price_impact, etc.
    evidence: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    # Human-readable description
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # False Positive Feedback Loop
    is_false_positive: Mapped[bool] = mapped_column(default=False, server_default="false", nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    # Relationship
    investigation: Mapped["Investigation"] = relationship("Investigation", back_populates="alerts")
